services:
  acestream-server:
    image: acestream-server:stable
    container_name: acestream-server
    user: 1000:1000
    restart: "unless-stopped"
    ports:
      - 6878:6878
    volumes:
      - ./tmp:/dev/disk/by-id
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    volumes:
      - ./config:/config
      - ./cache:/cache
      - type: bind
        source: /your/media/path
        target: /media
    restart: 'unless-stopped'
    ports:
      - 8096:8096
    extra_hosts:
      - 'host.docker.internal:host-gateway'
